;;;; test/cli-test.lisp - CLI behavior tests

(require :asdf)

;; Add repo root directory to ASDF load path.
(let* ((this-file (or *load-truename* *load-pathname*))
       (test-dir (uiop:pathname-directory-pathname this-file))
       (repo-root (uiop:pathname-parent-directory-pathname test-dir)))
  (push repo-root asdf:*central-registry*))

;; Load CLPM
(format t "Loading CLPM...~%")
(handler-case
    (asdf:load-system :clpm)
  (error (c)
    (format *error-output* "Failed to load CLPM: ~A~%" c)
    (sb-ext:exit :code 1)))

(format t "CLPM loaded successfully.~%~%")

(defun fail (fmt &rest args)
  (apply #'format *error-output* (concatenate 'string fmt "~%") args)
  (sb-ext:exit :code 1))

(defun assert-eql (expected actual)
  (unless (eql expected actual)
    (fail "Assertion failed: expected ~S, got ~S" expected actual)))

(defun assert-string= (expected actual)
  (unless (string= expected actual)
    (fail "Assertion failed: expected ~S, got ~S" expected actual)))

(defun sorted-external-symbol-names (package-name)
  (let ((names '()))
    (do-external-symbols (sym package-name)
      (push (symbol-name sym) names))
    (sort names #'string<)))

(defun assert-equal (expected actual)
  (unless (equal expected actual)
    (fail "Assertion failed: expected ~S, got ~S" expected actual)))

(defun external-symbol-names (package-name)
  (let ((names '()))
    (do-external-symbols (sym (find-package package-name))
      (push (symbol-name sym) names))
    (sort names #'string<)))

(defun run-cli-captured (args)
  (let ((out (make-string-output-stream))
        (err (make-string-output-stream)))
    (let ((*standard-output* out)
          (*error-output* err))
      (let ((code (clpm:run-cli args)))
        (values code
                (get-output-stream-string out)
                (get-output-stream-string err))))))

(format t "Testing --help...~%")
(assert-eql 0 (clpm:run-cli '("--help")))
(format t "  --help PASSED~%")

(format t "Testing bare clpm is help only...~%")
(multiple-value-bind (bare-code bare-out bare-err)
    (run-cli-captured '())
  (multiple-value-bind (help-code help-out help-err)
      (run-cli-captured '("help"))
    (assert-eql 0 bare-code)
    (assert-eql help-code bare-code)
    (assert-string= help-out bare-out)
    (assert-string= help-err bare-err)))
(format t "  Bare help PASSED~%")

(format t "Testing terminal root options do not mask trailing args...~%")
(dolist (args '(("--version" "--json")
                ("--help" "deps")
                ("deps" "--help" "bogus")
                ("project" "new" "--help" "--json")))
  (multiple-value-bind (code _out err)
      (run-cli-captured args)
    (declare (ignore _out))
    (assert-eql 1 code)
    (unless (search "Unexpected argument after" err)
      (fail "Expected terminal option trailing-arg rejection, got: ~A" err))))
(multiple-value-bind (code _out err)
    (run-cli-captured '("deps" "--version"))
  (declare (ignore _out))
  (assert-eql 1 code)
  (unless (search "Unknown deps subcommand" err)
    (fail "Expected command-local --version to reach deps parser, got: ~A" err)))
(format t "  Terminal root options PASSED~%")

(format t "Testing global options must precede the command token...~%")
(dolist (case '((("help" "-v") "Unknown command")
                (("repl" "--insecure") "Unknown subcommand")
                (("repl" "--offline") "Unknown subcommand")
                (("deps" "sync" "--offline") "Unknown option: --offline")
                (("deps" "sync" "--jobs" "4") "Unknown option: --jobs")
                (("run" "--lisp" "sbcl") "Unknown run operation: --lisp")))
  (destructuring-bind (args expected) case
    (multiple-value-bind (code _out err)
        (run-cli-captured args)
      (declare (ignore _out))
      (assert-eql 1 code)
      (unless (search expected err)
        (fail "Expected post-command global option to stay command-local (~S), got: ~A"
              expected err)))))
(format t "  Global option placement PASSED~%")

(format t "Testing unknown command...~%")
(assert-eql 1 (clpm:run-cli '("unknown-command")))
(format t "  Unknown command PASSED~%")

(format t "Testing nullary commands reject trailing args...~%")
(multiple-value-bind (code _out err)
    (run-cli-captured '("doctor" "extra"))
  (declare (ignore _out))
  (assert-eql 1 code)
  (unless (search "Usage: clpm doctor" err)
    (fail "Expected doctor trailing-arg rejection, got: ~A" err)))
(format t "  Nullary command arity PASSED~%")

(format t "Testing public command handler exports...~%")
(assert-equal '("CMD-DEPS" "CMD-DOCTOR" "CMD-HELP" "CMD-PROJECT"
                "CMD-REGISTRY" "CMD-REPL" "CMD-RUN" "CMD-SKILL"
                "CMD-STORE")
              (external-symbol-names "CLPM.COMMANDS"))
(assert-equal '("MAIN" "RUN-CLI")
              (external-symbol-names "CLPM"))
(dolist (name '("CMD-PROJECT" "CMD-DEPS" "CMD-REGISTRY" "CMD-RUN"
                "CMD-STORE" "CMD-REPL" "CMD-SKILL" "CMD-HELP"
                "CMD-DOCTOR"))
  (multiple-value-bind (_symbol status)
      (find-symbol name "CLPM.COMMANDS")
    (declare (ignore _symbol))
    (assert-eql :external status)))
(dolist (name '("CMD-INIT" "CMD-NEW" "CMD-ADD" "CMD-REMOVE"
                "CMD-SEARCH" "CMD-INFO" "CMD-TREE" "CMD-WHY"
                "CMD-RESOLVE" "CMD-FETCH" "CMD-BUILD" "CMD-INSTALL"
                "CMD-UPDATE" "CMD-WORKSPACE" "CMD-EXEC" "CMD-TEST"
                "CMD-PACKAGE" "CMD-CLEAN" "CMD-GC" "CMD-SCRIPTS"
                "CMD-AUDIT" "CMD-SBOM" "CMD-KEYS" "CMD-PUBLISH"))
  (multiple-value-bind (_symbol status)
      (find-symbol name "CLPM.COMMANDS")
    (declare (ignore _symbol))
    (assert-eql :internal status)))
(assert-equal '("CMD-DEPS" "CMD-DOCTOR" "CMD-HELP" "CMD-PROJECT"
                "CMD-REGISTRY" "CMD-REPL" "CMD-RUN" "CMD-SKILL"
                "CMD-STORE")
              (sorted-external-symbol-names "CLPM.COMMANDS"))
(assert-equal '("MAIN" "RUN-CLI")
              (sorted-external-symbol-names "CLPM"))
(format t "  Public handler exports PASSED~%")

(format t "Testing JSON option scope...~%")
(dolist (args '(("repl" "--json")
                ("--json" "repl")
                ("--json")))
  (multiple-value-bind (code _out err)
      (run-cli-captured args)
    (declare (ignore _out))
    (assert-eql 1 code)
    (unless (or (search "Unknown subcommand: --json" err)
                (search "Unknown option: --json" err))
      (fail "Expected inert --json to be rejected, got: ~A" err))))
(format t "  JSON option scope PASSED~%")

(format t "Testing insecure option scope...~%")
(dolist (args '(("--insecure" "help")
                ("--insecure" "--help")
                ("--insecure" "--version")))
  (multiple-value-bind (code _out err)
      (run-cli-captured args)
    (declare (ignore _out))
    (assert-eql 1 code)
    (unless (search "--insecure only applies" err)
      (fail "Expected inert --insecure to be rejected, got: ~A" err))))
(format t "  Insecure option scope PASSED~%")

(format t "Testing offline option scope...~%")
(dolist (args '(("--offline" "help")
                ("--offline" "deps" "sync" "--to" "lock")))
  (multiple-value-bind (code _out err)
      (run-cli-captured args)
    (declare (ignore _out))
    (assert-eql 1 code)
    (unless (search "--offline only applies" err)
      (fail "Expected inert --offline to be rejected, got: ~A" err))))
(format t "  Offline option scope PASSED~%")

(format t "Testing jobs option scope...~%")
(dolist (args '(("--jobs" "4" "help")
                ("-j" "4" "repl")
                ("--jobs" "2" "deps" "sync" "--to" "lock")))
  (multiple-value-bind (code _out err)
      (run-cli-captured args)
    (declare (ignore _out))
    (assert-eql 1 code)
    (unless (search "--jobs only applies" err)
      (fail "Expected inert --jobs to be rejected, got: ~A" err))))
(format t "  Jobs option scope PASSED~%")

(format t "Testing lisp option scope...~%")
(dolist (args '(("--lisp" "sbcl" "help")
                ("--lisp" "sbcl" "repl")
                ("--lisp" "sbcl" "deps" "sync" "--to" "source")))
  (multiple-value-bind (code _out err)
      (run-cli-captured args)
    (declare (ignore _out))
    (assert-eql 1 code)
    (unless (search "--lisp only applies" err)
      (fail "Expected inert --lisp to be rejected, got: ~A" err))))
(format t "  Lisp option scope PASSED~%")

(format t "Testing optional dependency option scope...~%")
(dolist (args '(("--with-optional" "foo" "help")
                ("--with-all-optional" "repl")))
  (multiple-value-bind (code _out err)
      (run-cli-captured args)
    (declare (ignore _out))
    (assert-eql 1 code)
    (unless (search "optional dependency flags only apply" err)
      (fail "Expected inert optional-dependency flag to be rejected, got: ~A" err))))
(format t "  Optional dependency option scope PASSED~%")

(format t "Testing fetch tuning option scope...~%")
(dolist (args '(("--fetch-retries" "2" "help")
                ("--fetch-timeout" "3" "repl")))
  (multiple-value-bind (code _out err)
      (run-cli-captured args)
    (declare (ignore _out))
    (assert-eql 1 code)
    (unless (search "fetch tuning only applies" err)
      (fail "Expected inert fetch tuning to be rejected, got: ~A" err))))
(dolist (args '(("--fetch-retries" "2" "deps" "search" "alexandria")
                ("--fetch-timeout" "3" "registry" "update")
                ("--fetch-timeout" "3" "registry" "trust" "refresh")))
  (multiple-value-bind (command command-args options)
      (clpm::parse-args args)
    (handler-case
        (clpm::validate-option-scope command command-args options)
      (clpm.errors:clpm-user-error (c)
        (fail "Expected fetch tuning to be accepted for ~S, got: ~A"
              args c)))))
(format t "  Fetch tuning option scope PASSED~%")

(format t "Testing workspace target option scope...~%")
(dolist (args '(("--package" "app" "help")
                ("--package" "app" "--version")
                ("--package" "app" "doctor")
                ("--package" "app" "skill")
                ("--package" "app" "project" "init")
                ("--package" "app" "registry" "list")
                ("--package" "app" "store" "gc")))
  (multiple-value-bind (code _out err)
      (run-cli-captured args)
    (declare (ignore _out))
    (assert-eql 1 code)
    (unless (search "workspace member target only applies" err)
      (fail "Expected inert workspace target to be rejected, got: ~A" err))))
(dolist (args '(("--package" "app" "project" "package")
                ("--package" "app" "deps" "sync")
                ("--package" "app" "registry" "publish")
                ("--package" "app" "run")
                ("--package" "app" "repl" "daemon")
                ("--package" "app" "store" "clean")))
  (multiple-value-bind (command command-args options)
      (clpm::parse-args args)
    (handler-case
        (clpm::validate-option-scope command command-args options)
      (clpm.errors:clpm-user-error (c)
        (fail "Expected workspace target to be accepted for ~S, got: ~A"
              args c)))))
(format t "  Workspace target option scope PASSED~%")

(format t "Testing run-program :timeout keyword...~%")
(multiple-value-bind (output error-output exit-code)
    (clpm.platform:run-program (list "sh" "-c" "exit 0") :timeout 1)
  (declare (ignore output error-output))
  (assert-eql 0 exit-code))
(format t "  run-program :timeout PASSED~%")

(format t "~%CLI tests PASSED!~%")
(sb-ext:exit :code 0)
