;;;; test/readme-docs-test.lisp - README command surface checks.

(require :asdf)

(defparameter *repo-root*
  (let* ((this-file (or *load-truename* *load-pathname*))
         (test-dir (uiop:pathname-directory-pathname this-file)))
    (uiop:pathname-parent-directory-pathname test-dir)))

(defun fail (fmt &rest args)
  (apply #'format *error-output* (concatenate 'string "FAIL: " fmt "~%") args)
  (sb-ext:exit :code 1))

(defun assert-contains (haystack needle)
  (unless (and (stringp haystack)
               (search needle haystack :test #'char-equal))
    (fail "expected README to contain ~S" needle)))

(defun assert-not-contains (haystack needle)
  (when (and (stringp haystack)
             (search needle haystack :test #'char-equal))
    (fail "README still contains stale command text ~S" needle)))

(defun read-file-string (path)
  (with-open-file (s path :direction :input :external-format :utf-8)
    (let ((text (make-string (file-length s))))
      (read-sequence text s)
      text)))

(let ((readme (read-file-string (merge-pathnames "README.md" *repo-root*))))
  (format t "Testing README REPL command docs...~%")
  (assert-contains readme "call find-definition")
  (assert-contains readme "call xref")
  (assert-not-contains readme "find-definitions")
  (assert-not-contains readme "who-calls")
  (assert-not-contains readme "help --method eval")
  (assert-not-contains readme "legacy comments")
  (assert-contains readme "Scoped options must appear before the command token.")
  (assert-contains readme "clpm project new <name> --workspace [--dir <path>]")
  (assert-contains readme "clpm project new <name> --bin\\|--lib [--template <template>] --member-of <workspace-dir>")
  (assert-contains readme "clpm project new <name> --template coalton [--dir <path>\\|--member-of <workspace-dir>]")
  (assert-contains readme "clpm project workspace add <member> [--dir <path>]")
  (assert-contains readme "clpm deps add [--dev\\|--test] [--any\\|--caret] [--path <dir>\\|--workspace <member>\\|--git <url> --ref <ref>] [<system>...]")
  (assert-contains readme "clpm deps remove [--dev\\|--test] [--workspace <member>] [<system>]")
  (assert-contains readme "clpm deps update [--workspace <member>] [system ...]")
  (assert-contains readme "clpm [-p <member>] deps why [--workspace <member>] [<system>]")
  (assert-contains readme "clpm registry trust refresh <name>")
  (assert-contains readme "clpm repl eval <form> --debug [debug-options]")
  (assert-not-contains readme "clpm project workspace <init\\|add\\|remove\\|list> ...")
  (assert-not-contains readme "clpm registry <add\\|list\\|update\\|trust\\|init\\|key\\|publish> ...")
  (assert-not-contains readme "clpm repl <daemon\\|eval\\|call> ...")
  (assert-contains readme "Public keys embedded under `registry/keys/` are distributable metadata, not a")
  (assert-not-contains readme "ed25519:abcd")
  (assert-not-contains readme "ed25519:...")
  (format t "  README REPL docs PASSED~%"))

(let ((bridge (read-file-string (merge-pathnames "BRIDGE.md" *repo-root*))))
  (format t "Testing bridge design docs...~%")
  (assert-contains bridge "clpm repl eval FORM")
  (assert-contains bridge "pass `--json' for the raw JSON line")
  (assert-not-contains bridge "with `--pretty`")
  (assert-not-contains bridge "Default mode is raw JSON")
  (format t "  Bridge docs PASSED~%"))

(let ((skill (read-file-string
              (merge-pathnames ".claude/skills/clpm-repl-bridge.md"
                               *repo-root*))))
  (format t "Testing REPL skill docs...~%")
  (assert-contains skill "clpm repl daemon")
  (assert-contains skill "clpm help repl eval")
  (assert-not-contains skill "clpm repl-bridge")
  (assert-not-contains skill "help --method eval")
  (assert-not-contains skill ".clpm/repl-bridge")
  (format t "  REPL skill docs PASSED~%"))

(format t "~%README docs tests PASSED!~%")
(sb-ext:exit :code 0)
